on: [push]
permissions: write-all
jobs:
  sigma_code_scanning_run_steps:
    runs-on: ubuntu-latest
    container:
      image: eabddocker/sigma-private:latest
      options: --user root
      credentials: 
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.DOCKPASS }} 
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Sigma analysis
        run: sigma analyze --format github •
    
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: sigma-results.json
